// <auto-generated />
using Biblioteca.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biblioteca.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230623030848_tablasMigrate")]
    partial class tablasMigrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Biblioteca.Models.Autor", b =>
                {
                    b.Property<string>("codigoAutor")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NacionalidadAutor")
                        .HasColumnType("longtext");

                    b.Property<string>("nombreAutores")
                        .HasColumnType("longtext");

                    b.HasKey("codigoAutor");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("Biblioteca.Models.Docente", b =>
                {
                    b.Property<string>("codigoDocente")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FacultadDocente")
                        .HasColumnType("longtext");

                    b.Property<string>("NombreDocente")
                        .HasColumnType("longtext");

                    b.HasKey("codigoDocente");

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("Biblioteca.Models.Editorial", b =>
                {
                    b.Property<string>("codigoEditorial")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ContactoEditorial")
                        .HasColumnType("longtext");

                    b.Property<string>("TelefonoEditorial")
                        .HasColumnType("longtext");

                    b.Property<string>("nombreEditorial")
                        .HasColumnType("longtext");

                    b.HasKey("codigoEditorial");

                    b.ToTable("Editoriales");
                });

            modelBuilder.Entity("Biblioteca.Models.Genero", b =>
                {
                    b.Property<string>("idGenero")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NombreGenero")
                        .HasColumnType("longtext");

                    b.Property<string>("descripcionGenero")
                        .HasColumnType("longtext");

                    b.HasKey("idGenero");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("Biblioteca.Models.Libros", b =>
                {
                    b.Property<string>("codigoLibro")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("descripcionLibro")
                        .HasColumnType("longtext");

                    b.Property<int>("existenciasLibro")
                        .HasColumnType("int");

                    b.Property<string>("nombreLibro")
                        .HasColumnType("longtext");

                    b.Property<float>("precioLibro")
                        .HasColumnType("float");

                    b.HasKey("codigoLibro");

                    b.ToTable("Libros");
                });
#pragma warning restore 612, 618
        }
    }
}
