// <auto-generated />
using Biblioteca.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biblioteca.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230623023635_InitialMigrate")]
    partial class InitialMigrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Biblioteca.Models.Autor", b =>
                {
                    b.Property<string>("codigoAutor")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NacionalidadAutor")
                        .HasColumnType("longtext");

                    b.Property<string>("nombreAutores")
                        .HasColumnType("longtext");

                    b.HasKey("codigoAutor");

                    b.ToTable("Autores");
                });
#pragma warning restore 612, 618
        }
    }
}
